import test from 'node:test';
import assert from 'node:assert/strict';
import { openStore } from '../src/store.js';
import { integer, convert, money } from '../src/money.js';
import { fingerprint, invoiceIds, hash } from '../src/revisions.js';
import { candidateDigest, selectedInvoices } from '../src/source-selection.js';
import { sourceBundle, adjustmentLines, investigate, summary, booked } from '../src/accounting.js';
import { validateProposal } from '../src/validator.js';
import { importCase, chooseInvoiceSource } from '../src/cases.js';
import { decisionCard, decisionDesk, draftEvidenceRequest, brandWorkspace } from '../src/decisions.js';
import { addCredit, addCommunication, approve, reject, prepareReport, exportReport, runClose, safeError, recoverInterrupted } from '../src/workflow.js';

const rehearsal = { mode: 'extended deterministic test', investigate: async (_state, plan) => ({ text: plan.explanation, escalate: plan.status === 'blocked' }) };
const reviewer = p => ({ reviewer: 'Extended test controller', role: 'group_controller', revision: p.revision });
const latest = (store, id) => store.read().investigations.filter(p => p.invoiceId === id).at(-1);
const fresh = () => openStore(':memory:');

test('integer accepts safe minor-unit boundaries', () => { assert.equal(integer(0), 0); assert.equal(integer(1_000_000_000_000), 1_000_000_000_000); });
test('integer rejects fractions, non-numbers, unsafe values and excess magnitude', () => { for (const value of [1.2, '100', Number.MAX_SAFE_INTEGER, -1_000_000_000_001]) assert.throws(() => integer(value)); });
test('convert preserves zero and sign at half-up boundaries', () => { assert.equal(convert(0, { n: 4, d: 5 }), 0); assert.equal(convert(5, { n: 1, d: 2 }), 3); assert.equal(convert(-5, { n: 1, d: 2 }), -3); });
test('convert rejects malformed or negative policy rates', () => { for (const rate of [null, {}, { n: 0, d: 1 }, { n: 1, d: 0 }, { n: -1, d: 1 }, { n: 1.5, d: 1 }]) assert.throws(() => convert(100, rate)); });
test('money formats minor units in the requested currency', () => { assert.equal(money(1_234_567), '$12,345.67'); assert.equal(money(99_00, 'GBP'), '£99.00'); });

test('invoiceIds are unique and sorted for stable workflow order', () => { const s = fresh(); try { const state = s.read(); state.documents.push({ ...state.documents[0], id: 'DUP', invoiceId: 'IC-1042' }); assert.deepEqual(invoiceIds(state), ['IC-1042', 'IC-1043', 'IC-1044', 'IC-1045', 'IC-1046', 'IC-1047']); } finally { s.close(); } });
test('scoped fingerprints change for evidence but not unrelated investigation records', () => { const s = fresh(); try { const before = fingerprint(s.read(), 'IC-1042'); s.update(state => { state.documents[0].body += ' amended'; }); assert.notEqual(fingerprint(s.read(), 'IC-1042'), before); } finally { s.close(); } });
test('hash is deterministic for equivalent JSON values', () => { assert.equal(hash({ a: 1, b: ['x'] }), hash({ a: 1, b: ['x'] })); assert.notEqual(hash({ a: 1 }), hash({ a: 2 })); });
test('candidateDigest changes when a conflicting invoice source arrives', () => { const s = fresh(); try { const before = candidateDigest(s.read(), 'IC-1042'); s.update(state => state.documents.push({ ...state.documents.find(d => d.invoiceId === 'IC-1042' && d.kind === 'invoice'), id: 'CONFLICT-X', amount: 1_300_000, sourceOnly: true })); assert.notEqual(candidateDigest(s.read(), 'IC-1042'), before); } finally { s.close(); } });
test('selectedInvoices returns the only candidate without a source decision', () => { const s = fresh(); try { assert.equal(selectedInvoices(s.read(), 'IC-1042').length, 1); } finally { s.close(); } });
test('selectedInvoices keeps all candidates until a current controller choice exists', () => { const s = fresh(); try { s.update(state => state.documents.push({ ...state.documents.find(d => d.invoiceId === 'IC-1042' && d.kind === 'invoice'), id: 'CONFLICT-Y', amount: 1_300_000 })); assert.equal(selectedInvoices(s.read(), 'IC-1042').length, 2); } finally { s.close(); } });

test('sourceBundle blocks an unknown invoice reference', () => { const s = fresh(); try { assert.match(sourceBundle(s.read(), 'MISSING').blocked, /No structured invoice/); } finally { s.close(); } });
test('sourceBundle blocks a non-USD invoice', () => { const s = fresh(); try { s.update(state => { state.documents.find(d => d.invoiceId === 'IC-1042' && d.kind === 'invoice').currency = 'EUR'; }); assert.match(sourceBundle(s.read(), 'IC-1042').blocked, /USD/); } finally { s.close(); } });
test('sourceBundle blocks disputed service acceptance', () => { const s = fresh(); try { assert.match(sourceBundle(s.read(), 'IC-1047').blocked, /disputed/); } finally { s.close(); } });
test('sourceBundle blocks a credit with mismatched parties or currency', () => { const s = fresh(); try { s.update(state => state.documents.push({ id: 'BAD-CREDIT', invoiceId: 'IC-1042', kind: 'credit_note', seller: 'UK', buyer: 'US', currency: 'EUR', amount: 1, version: 1 })); assert.match(sourceBundle(s.read(), 'IC-1042').blocked, /parties or currency/); } finally { s.close(); } });
test('sourceBundle blocks credits greater than the invoice amount', () => { const s = fresh(); try { s.update(state => state.documents.push({ id: 'BIG-CREDIT', invoiceId: 'IC-1042', kind: 'credit_note', seller: 'US', buyer: 'UK', currency: 'USD', amount: 1_200_001, version: 1 })); assert.match(sourceBundle(s.read(), 'IC-1042').blocked, /exceed/); } finally { s.close(); } });
test('adjustmentLines emits no entries for a reconciled delta', () => { const s = fresh(); try { assert.deepEqual(adjustmentLines(s.read().entities[0], 'seller', 0), []); } finally { s.close(); } });
test('adjustmentLines reverses accounts for a negative seller delta', () => { const s = fresh(); try { const lines = adjustmentLines(s.read().entities[0], 'seller', -100); assert.equal(lines[0].account, 'IC_RECEIVABLE'); assert.equal(lines[0].credit, 100); assert.equal(lines[1].account, 'SERVICE_REVENUE'); assert.equal(lines[1].debit, 100); } finally { s.close(); } });
test('adjustmentLines reverses accounts for a negative buyer delta', () => { const s = fresh(); try { const lines = adjustmentLines(s.read().entities[1], 'buyer', -100); assert.equal(lines[0].account, 'SERVICE_EXPENSE'); assert.equal(lines[0].credit, 100); assert.equal(lines[1].account, 'IC_PAYABLE'); assert.equal(lines[1].debit, 100); } finally { s.close(); } });

test('investigate returns a blocked controlled stop for IC-1047', () => { const s = fresh(); try { const p = investigate(s.read(), 'IC-1047'); assert.equal(p.status, 'blocked'); assert.equal(p.entries.length, 0); assert.match(p.explanation, /signed confirmation|disputed/i); } finally { s.close(); } });
test('summary exposes the initial reconciliation and exception states', () => { const s = fresh(); try { const result = summary(s.read()); assert.equal(result.cases.length, 6); assert.equal(result.cases.find(c => c.invoiceId === 'IC-1046').status, 'matched'); assert.equal(result.cases.find(c => c.invoiceId === 'IC-1047').status, 'blocked'); } finally { s.close(); } });
test('decisionCard rejects an unknown invoice and decisionDesk covers every case', () => { const s = fresh(); try { assert.throws(() => decisionCard(s.read(), 'UNKNOWN'), /Unknown invoice/); assert.equal(decisionDesk(s.read()).length, 6); } finally { s.close(); } });
test('brandWorkspace is idempotent and preserves accounting state', () => { const s = fresh(); try { const before = fingerprint(s.read()); brandWorkspace(s); const once = s.read(); brandWorkspace(s); assert.equal(fingerprint(s.read()), fingerprint(once)); assert.equal(fingerprint(s.read()), before); } finally { s.close(); } });

test('importCase rejects malformed identifiers and non-USD payloads', () => { const s = fresh(); try { const base = { invoiceId: 'NEW-1', sourceId: 'SRC-1', title: 'New service', seller: 'US', buyer: 'UK', amount: 100, currency: 'USD', period: '2026-08', body: 'accepted' }; for (const input of [{ ...base, invoiceId: 'bad id' }, { ...base, currency: 'EUR' }, { ...base, amount: 1.5 }]) assert.throws(() => importCase(s, input)); } finally { s.close(); } });
test('importCase rejects wrong period and same-entity parties', () => { const s = fresh(); try { const base = { invoiceId: 'NEW-2', sourceId: 'SRC-2', title: 'New service', seller: 'US', buyer: 'UK', amount: 100, currency: 'USD', period: '2026-08', body: 'accepted' }; assert.throws(() => importCase(s, { ...base, period: '2026-07' })); assert.throws(() => importCase(s, { ...base, seller: 'US', buyer: 'US', sourceId: 'SRC-3' })); } finally { s.close(); } });
test('source-only imports cannot alter opening balances', () => { const s = fresh(); try { const base = { invoiceId: 'NEW-3', sourceId: 'SRC-3', title: 'New service', seller: 'US', buyer: 'UK', amount: 100, currency: 'USD', period: '2026-08', body: 'accepted' }; importCase(s, base); assert.throws(() => importCase(s, { ...base, sourceId: 'SRC-4', sourceOnly: true, sellerBooked: 1 })); } finally { s.close(); } });
test('chooseInvoiceSource requires a current controller reason and fingerprint', () => { const s = fresh(); try { assert.throws(() => chooseInvoiceSource(s, { invoiceId: 'IC-1042', selectedSourceId: 'DOC-IC-1042', sourceFingerprint: fingerprint(s.read(), 'IC-1042'), reviewer: 'x', role: 'group_controller', reason: 'short' })); } finally { s.close(); } });

test('evidence request rejects invalid owners and preserves source state', () => { const s = fresh(); try { const before = fingerprint(s.read()); assert.throws(() => draftEvidenceRequest(s, { invoiceId: 'IC-1047', sourceFingerprint: before, owner: '', reviewer: 'Controller' })); assert.equal(fingerprint(s.read()), before); } finally { s.close(); } });
test('credit import rejects unknown invoice and malformed source reference', () => { const s = fresh(); try { assert.throws(() => addCredit(s, { invoiceId: 'UNKNOWN', amount: 1, reason: 'x' }), /Resolve conflicting invoice sources/); assert.throws(() => addCredit(s, { invoiceId: 'IC-1042', amount: 1, reason: 'x', sourceId: 'bad id' }), /stable source/); } finally { s.close(); } });
test('communication import accepts trimmed untrusted text and invalidates the invoice', () => { const s = fresh(); try { const doc = addCommunication(s, { invoiceId: 'IC-1042', kind: 'email', title: ' Follow up ', body: ' Confirmed by source owner ' }); assert.equal(doc.title, 'Follow up'); assert.equal(doc.source, 'User-imported text; untrusted evidence'); assert.equal(s.read().events.at(-1).type, 'evidence.changed'); } finally { s.close(); } });
test('communication import rejects unsupported kinds and oversized text', () => { const s = fresh(); try { assert.throws(() => addCommunication(s, { invoiceId: 'IC-1042', kind: 'slack', title: 'x', body: 'y' })); assert.throws(() => addCommunication(s, { invoiceId: 'IC-1042', kind: 'email', title: 'x', body: 'a'.repeat(20_001) })); } finally { s.close(); } });

test('approval rejects missing proposal, wrong revision and non-controller role', async () => { const s = fresh(); try { await runClose(s, rehearsal, 'IC-1042'); const p = latest(s, 'IC-1042'); assert.throws(() => approve(s, 'missing', reviewer(p)), /Proposal not found/); assert.throws(() => approve(s, p.id, { ...reviewer(p), revision: p.revision + 1 }), /revision/); assert.throws(() => approve(s, p.id, { ...reviewer(p), role: 'entity_accountant' }), /group controller/); } finally { s.close(); } });
test('approval rejects a blocked IC-1047 proposal without posting', async () => { const s = fresh(); try { await runClose(s, rehearsal, 'IC-1047'); const p = latest(s, 'IC-1047'); assert.equal(p.status, 'blocked'); assert.throws(() => approve(s, p.id, reviewer(p)), /Only a current proposal/); assert.equal(s.read().journals.filter(j => j.kind === 'correction').length, 0); } finally { s.close(); } });
test('reject requires a reason and records reviewer feedback', async () => { const s = fresh(); try { await runClose(s, rehearsal, 'IC-1042'); const p = latest(s, 'IC-1042'); assert.throws(() => reject(s, p.id, { reviewer: 'Controller', reason: '' })); reject(s, p.id, { reviewer: 'Controller', reason: 'Need signed source confirmation' }); assert.equal(s.read().feedback.length, 1); assert.equal(s.read().events.at(-1).type, 'approval.rejected'); } finally { s.close(); } });
test('safeError redacts provider secrets and limits error length', () => { const previous = process.env.TEST_API_KEY; process.env.TEST_API_KEY = 'secret-token-value'; try { const safe = safeError(new Error('secret-token-value ' + 'x'.repeat(600))); assert.equal(safe.includes('secret-token-value'), false); assert.ok(safe.length <= 400); } finally { if (previous === undefined) delete process.env.TEST_API_KEY; else process.env.TEST_API_KEY = previous; } });

test('prepareReport is provisional while IC-1047 remains unresolved', async () => { const s = fresh(); try { await runClose(s, rehearsal); const report = prepareReport(s); assert.equal(report.status, 'provisional'); assert.deepEqual(report.unresolved.map(x => x.invoiceId), ['IC-1042', 'IC-1043', 'IC-1044', 'IC-1045', 'IC-1047']); assert.equal(report.eliminations.length, 1); } finally { s.close(); } });
test('exportReport rejects an empty workspace and freezes prepared evidence', () => { const s = fresh(); try { assert.throws(() => exportReport(s), /not found/); const report = prepareReport(s); const exported = exportReport(s, report.id); assert.equal(exported.snapshotStatus, 'Evidence and ledger frozen at preparation'); assert.equal(exported.evidence.length, s.read().documents.length); } finally { s.close(); } });
test('booked computes functional balances with account direction', () => { const s = fresh(); try { assert.equal(booked(s.read(), 'IC-1042', 'US', 'IC_RECEIVABLE'), 1_200_000); assert.equal(booked(s.read(), 'IC-1042', 'US', 'SERVICE_REVENUE'), -1_200_000); } finally { s.close(); } });

test('validator rejects a proposal that omits one source document', async () => { const s = fresh(); try { await runClose(s, rehearsal, 'IC-1042'); const p = latest(s, 'IC-1042'); const altered = { ...p, evidenceIds: p.evidenceIds.slice(0, -1) }; const result = validateProposal(s.read(), altered); assert.equal(result.passed, false); assert.equal(result.checks.find(c => c.name === 'Evidence references').passed, false); } finally { s.close(); } });
test('validator rejects entries with two-sided or negative amounts', async () => { const s = fresh(); try { await runClose(s, rehearsal, 'IC-1042'); const p = latest(s, 'IC-1042'); const altered = { ...p, entries: p.entries.map((e, i) => i === 0 ? { ...e, debit: 1, credit: 1 } : i === 1 ? { ...e, debit: -1 } : e) }; const result = validateProposal(s.read(), altered); assert.equal(result.passed, false); assert.equal(result.checks.find(c => c.name === 'Exact minor units').passed, false); } finally { s.close(); } });
test('validator rejects unsupported accounts and currencies', async () => { const s = fresh(); try { await runClose(s, rehearsal, 'IC-1042'); const p = latest(s, 'IC-1042'); const altered = { ...p, entries: p.entries.map((e, i) => i === 0 ? { ...e, account: 'CASH', currency: 'EUR' } : e) }; const result = validateProposal(s.read(), altered); assert.equal(result.passed, false); assert.equal(result.checks.find(c => c.name === 'Allowed accounts and currency').passed, false); } finally { s.close(); } });
test('validator binds proposals to the current policy revision', async () => { const s = fresh(); try { await runClose(s, rehearsal, 'IC-1042'); const p = latest(s, 'IC-1042'); const altered = { ...p, policyVersion: p.policyVersion + 1 }; const result = validateProposal(s.read(), altered); assert.equal(result.passed, false); assert.equal(result.checks.find(c => c.name === 'Policy revision').passed, false); } finally { s.close(); } });

test('credit retry is idempotent and newer content preserves document history', () => { const s = fresh(); try { const first = addCredit(s, { invoiceId: 'IC-1042', amount: 100, reason: 'Approved rebate', sourceId: 'CN-RETRY', version: 1 }); const replay = addCredit(s, { invoiceId: 'IC-1042', amount: 100, reason: 'Approved rebate', sourceId: 'CN-RETRY', version: 1 }); assert.equal(replay.replayed, true); const revised = addCredit(s, { invoiceId: 'IC-1042', amount: 200, reason: 'Approved revised rebate', sourceId: 'CN-RETRY', version: 2 }); assert.equal(revised.version, 2); assert.equal(s.read().documentHistory.at(-1).id, first.id); } finally { s.close(); } });
test('credit source references cannot overwrite another document', () => { const s = fresh(); try { const invoiceDoc = s.read().documents.find(d => d.invoiceId === 'IC-1042' && d.kind === 'invoice'); assert.throws(() => addCredit(s, { invoiceId: 'IC-1042', amount: 100, reason: 'Collision', sourceId: invoiceDoc.id }), /another document/); } finally { s.close(); } });
test('communication evidence rejects an unknown invoice without mutation', () => { const s = fresh(); try { const before = s.read().documents.length; assert.throws(() => addCommunication(s, { invoiceId: 'UNKNOWN', kind: 'email', title: 'x', body: 'y' }), /Unknown invoice/); assert.equal(s.read().documents.length, before); } finally { s.close(); } });

test('controller source choice resolves a conflict and records its digest', () => { const s = fresh(); try { const base = s.read().documents.find(d => d.invoiceId === 'IC-1042' && d.kind === 'invoice'); s.update(state => state.documents.push({ ...base, id: 'INV-CONFLICT', amount: 1_250_000, sourceOnly: true })); const choice = chooseInvoiceSource(s, { invoiceId: 'IC-1042', selectedSourceId: base.id, sourceFingerprint: fingerprint(s.read(), 'IC-1042'), reviewer: 'Controller', role: 'group_controller', reason: 'Signed source is authoritative after review' }); assert.equal(choice.selectedSourceId, base.id); assert.equal(s.read().sourceDecisions.length, 1); assert.equal(s.read().events.at(-1).type, 'source.selected'); } finally { s.close(); } });
test('invalidate marks downstream reports stale while retaining historical approvals', async () => { const s = fresh(); try { await runClose(s, rehearsal, 'IC-1042'); const p = latest(s, 'IC-1042'); const report = prepareReport(s); approve(s, p.id, reviewer(p)); addCredit(s, { invoiceId: 'IC-1042', amount: 100, reason: 'Late credit', sourceId: 'CN-LATE', version: 1 }); const state = s.read(); assert.equal(state.investigations.find(x => x.id === p.id).status, 'posted'); assert.equal(state.reports.find(x => x.id === report.id).stale, true); assert.ok(state.investigations.find(x => x.id === p.id).approval); assert.ok(state.lastChange.affected.some(x => x.kind === 'approval')); } finally { s.close(); } });

test('decision cards distinguish missing evidence, no action and approval', async () => { const s = fresh(); try { assert.equal(decisionCard(s.read(), 'IC-1047').kind, 'missing_evidence'); assert.equal(decisionCard(s.read(), 'IC-1046').kind, 'no_action'); await runClose(s, rehearsal, 'IC-1042'); assert.equal(decisionCard(s.read(), 'IC-1042').kind, 'approve_correction'); } finally { s.close(); } });
test('decision card exposes a current challenge result and evidence references', async () => { const s = fresh(); try { await runClose(s, rehearsal, 'IC-1042'); const card = decisionCard(s.read(), 'IC-1042'); assert.equal(card.challenge.method, 'Deterministic independent checks; not another model'); assert.ok(card.sourceIds.length > 0); assert.ok(card.validation.checks.length >= 5); } finally { s.close(); } });
test('runClose rejects an unknown selected invoice before creating a run', async () => { const s = fresh(); try { await assert.rejects(() => runClose(s, rehearsal, 'UNKNOWN'), /Unknown invoice/); assert.equal(s.read().runs.length, 0); } finally { s.close(); } });
test('failed agent runs are persisted as failed with no correction journals', async () => { const s = fresh(); try { const failing = { mode: 'failure-test', investigate: async () => { throw new Error('provider unavailable'); } }; await runClose(s, failing, 'IC-1042'); const run = s.read().runs.at(-1); assert.equal(run.status, 'failed'); assert.match(run.error, /provider unavailable/); assert.equal(s.read().journals.filter(j => j.kind === 'correction').length, 0); } finally { s.close(); } });
test('default close run checkpoints every invoice and completes with one blocked case', async () => { const s = fresh(); try { await runClose(s, rehearsal); const run = s.read().runs.at(-1); assert.equal(run.status, 'completed'); assert.equal(run.completed, run.total); assert.equal(run.total, 6); assert.equal(s.read().investigations.filter(p => p.status === 'blocked').length, 1); } finally { s.close(); } });
test('draft evidence requests replay by revision-bound idempotency key', () => { const s = fresh(); try { const fp = fingerprint(s.read(), 'IC-1047'); const first = draftEvidenceRequest(s, { invoiceId: 'IC-1047', sourceFingerprint: fp, owner: 'Evidence owner', reviewer: 'Controller' }); const replay = draftEvidenceRequest(s, { invoiceId: 'IC-1047', sourceFingerprint: fp, owner: 'Evidence owner', reviewer: 'Controller' }); assert.equal(replay.replayed, true); assert.equal(s.read().evidenceRequests.length, 1); assert.equal(first.sent, false); } finally { s.close(); } });
test('prepared report becomes stale when a later communication changes evidence', () => { const s = fresh(); try { const report = prepareReport(s); addCommunication(s, { invoiceId: 'IC-1047', kind: 'meeting', title: 'Acceptance follow-up', body: 'Signed confirmation remains outstanding.' }); const exported = exportReport(s, report.id); assert.equal(exported.stale, true); assert.equal(exported.snapshotStatus, 'Evidence and ledger frozen at preparation'); } finally { s.close(); } });
test('recovery marks a running run interrupted and emits an audit event', () => { const s = fresh(); try { s.update(state => state.runs.push({ id: 'RUN-RECOVER', status: 'running', invoiceIds: ['IC-1042'], completed: 0, total: 1 })); const before = s.read().events.length; recoverInterrupted(s); assert.equal(s.read().runs.at(-1).status, 'interrupted'); assert.equal(s.read().events.length, before + 1); assert.equal(s.read().events.at(-1).type, 'run.interrupted'); } finally { s.close(); } });
